spring:

  datasource:
    url: jdbc:mysql://localhost:3306/clinica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Senha@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
    #property-naming-strategy: SNAKE_CASE

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: INFO
    com.saude.api: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Configuração de CORS personalizada (você ainda precisa configurar o filtro em Java)
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true